// Generated by gencpp from file am2315/Environment.msg
// DO NOT EDIT!


#ifndef AM2315_MESSAGE_ENVIRONMENT_H
#define AM2315_MESSAGE_ENVIRONMENT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace am2315
{
template <class ContainerAllocator>
struct Environment_
{
  typedef Environment_<ContainerAllocator> Type;

  Environment_()
    : header()
    , temperature(0.0)
    , humidity(0.0)  {
    }
  Environment_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , temperature(0.0)
    , humidity(0.0)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef double _temperature_type;
  _temperature_type temperature;

   typedef double _humidity_type;
  _humidity_type humidity;





  typedef boost::shared_ptr< ::am2315::Environment_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::am2315::Environment_<ContainerAllocator> const> ConstPtr;

}; // struct Environment_

typedef ::am2315::Environment_<std::allocator<void> > Environment;

typedef boost::shared_ptr< ::am2315::Environment > EnvironmentPtr;
typedef boost::shared_ptr< ::am2315::Environment const> EnvironmentConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::am2315::Environment_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::am2315::Environment_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::am2315::Environment_<ContainerAllocator1> & lhs, const ::am2315::Environment_<ContainerAllocator2> & rhs)
{
  return lhs.header == rhs.header &&
    lhs.temperature == rhs.temperature &&
    lhs.humidity == rhs.humidity;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::am2315::Environment_<ContainerAllocator1> & lhs, const ::am2315::Environment_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace am2315

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::am2315::Environment_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::am2315::Environment_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am2315::Environment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::am2315::Environment_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am2315::Environment_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::am2315::Environment_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::am2315::Environment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b4e9cf4dd4a8fb88b9ee33bf3f10d35b";
  }

  static const char* value(const ::am2315::Environment_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb4e9cf4dd4a8fb88ULL;
  static const uint64_t static_value2 = 0xb9ee33bf3f10d35bULL;
};

template<class ContainerAllocator>
struct DataType< ::am2315::Environment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "am2315/Environment";
  }

  static const char* value(const ::am2315::Environment_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::am2315::Environment_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n"
"float64 temperature\n"
"float64 humidity\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/Header\n"
"# Standard metadata for higher-level stamped data types.\n"
"# This is generally used to communicate timestamped data \n"
"# in a particular coordinate frame.\n"
"# \n"
"# sequence ID: consecutively increasing ID \n"
"uint32 seq\n"
"#Two-integer timestamp that is expressed as:\n"
"# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n"
"# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n"
"# time-handling sugar is provided by the client library\n"
"time stamp\n"
"#Frame this data is associated with\n"
"string frame_id\n"
;
  }

  static const char* value(const ::am2315::Environment_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::am2315::Environment_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.temperature);
      stream.next(m.humidity);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Environment_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::am2315::Environment_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::am2315::Environment_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "temperature: ";
    Printer<double>::stream(s, indent + "  ", v.temperature);
    s << indent << "humidity: ";
    Printer<double>::stream(s, indent + "  ", v.humidity);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AM2315_MESSAGE_ENVIRONMENT_H
